# ===================================================================
# CONFIGURACIÓN DE CONEXIÓN A LA BASE DE DATOS
# ===================================================================

# Especifica la URL de conexión JDBC a la base de datos MySQL local
# El formato es jdbc:mysql://[host]:[puerto]/[nombre_base_datos]
# Hemos agregado 'createDatabaseIfNotExist=true' para que MySQL cree la BD automáticamente si no existe la primera vez.
spring.datasource.url=jdbc:mysql://localhost:3306/mvc_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

# Nombre de usuario del servidor MySQL (típico para entorno local)
spring.datasource.username=root

# Contraseña del usuario MySQL. (Ajusta este valor si tu root en local no tiene clave, por ejemplo en XAMPP suele ir vacío)
spring.datasource.password=root

# Indica explícitamente el nombre de la clase del Driver de MySQL para establecer la conexión (Spring Boot 3 usa com.mysql.cj.jdbc.Driver)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===================================================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===================================================================

# Estrategia de generación/actualización del esquema de la base de datos basada en las entidades de Java.
# 'update': Actualiza la estructura de las tablas en la BD si agregamos atributos en las clases, y crea las tablas si no existen.
# Excelente para desarrollo rápido, pero en producción se suele utilizar 'validate' o 'none'.
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de la aplicación todas las consultas SQL nativas que Hibernate ejecuta internamente (muy útil para depuración)
spring.jpa.show-sql=true

# Da un formato más legible (indentado y estructurado) a las consultas SQL que se imprimen en la consola por show-sql
spring.jpa.properties.hibernate.format_sql=true

# Establece el dialecto específico de SQL que Hibernate debe usar para hablar con MySQL.
# Le permite a Hibernate optimizar sus consultas y definir correctamente los tipos de datos propios de MySQL.
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
